backend:
  name: git-gateway
  branch: main   # GitHub 브랜치명 (보통 main)

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "페이지 콘텐츠"
    files:
      - file: "index.html"
        label: "메인 페이지"
        name: "index"
        fields:
          - { label: "히어로 타이틀", name: "hero_title", widget: "string" }
          - { label: "히어로 서브타이틀", name: "hero_subtitle", widget: "string" }
          - { label: "소개 문단", name: "intro", widget: "text" }
